### ISSUE TITLE
parcel-resolver-typescript-module: Ts config error invalid_json

### ISSUE THREAD

**Issue by MaxAller** [caio-oliv/parcel-resolver-typescript-module#2]
The build normally works fine, but after adding this plugin I get `parcel-resolver-typescript-module: Ts config error invalid_json`. I'm using a variant of the tsconfig generated when you init a ts project, which has a lot of comments in the JSON, which isn't technically valid, but ts handles just fine. I think this module is having issues with that, though.

**Comment by caio-oliv** [comment]
Yeah, this error is thrown from parsing a invalid json (with [JSON.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)), which doesn't accept comments or trailing commas.

I published a new version (`0.1.9`) that uses [JSON5](https://json5.org/) to parse json files. This issue is probably fixed now.
